### ISSUE TITLE
ImportError: No module named 'urlparse'

### ISSUE THREAD

**Issue by Thomas-23** [jjyr/zerotest#7]
my python environment is a venv of python3.5 on the windows 8

after pip install zerotest
i just follow the tutorial
```
Usage
Start a local proxy to capture http traffic zerotest server https://api.github.com -f octocat.data
```
and the issue occurs:

```
(zeortest) E:\working\python\zeortest\Scripts>zerotest server https://api.github
.com -f octocat.data
Traceback (most recent call last):
  File "E:\working\python\zeortest\Scripts\zerotest-script.py", line 9, in <modu
le>
    load_entry_point('zerotest==1.0.2', 'console_scripts', 'zerotest')()
  File "E:\working\python\zeortest\lib\site-packages\pkg_resources\__init__.py",
 line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "E:\working\python\zeortest\lib\site-packages\pkg_resources\__init__.py",
 line 2630, in load_entry_point
    return ep.load()
  File "E:\working\python\zeortest\lib\site-packages\pkg_resources\__init__.py",
 line 2310, in load
    return self.resolve()
  File "E:\working\python\zeortest\lib\site-packages\pkg_resources\__init__.py",
 line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "E:\working\python\zeortest\lib\site-packages\zerotest\cli.py", line 6, i
n <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```

**Comment by jjyr** [comment]
Hi, zerotest is write in python2.7 , not yet support python3

**Comment by jjyr** [comment]
Should consider python3 support

**Comment by Thomas-23** [comment]
Yes, python3 is the future. Thanks for your answer

**Comment by jjyr** [comment]
[v1.1.2](https://github.com/jjyr/zerotest/releases/tag/v1.1.2) should fix python3 compatibility.
