### ISSUE TITLE
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'

### ISSUE THREAD

**Issue by allexeye** [jjyr/zerotest#8]
Got this 
```
INFO:zerotest.record.http_recorder:recorder service start, store http record to 'octocat.data'
INFO:werkzeug: * Running on http://127.0.0.1:7000/ (Press CTRL+C to quit)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43451)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 215, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 249, in handle_one_request
    elif self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 271, in log_error
    self.log('error', *args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 277, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 265, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
```

for ```curl "https://localhost:7000/api/2/storelist/10117" --insecure```
Any ideas what is that about?

**Comment by jjyr** [comment]
The address `localhost:7000` is a HTTP local proxy, can you try `curl "http://localhost:7000/api/2/storelist/10117"` and paste result?

**Comment by allexeye** [comment]
here it is:
```curl: (35) Unknown SSL protocol error in connection to localhost:7000```
with the same error

**Comment by jjyr** [comment]
Seems like a werkzeug bug, you send https request to http proxy server, werkzeug cannot parse request and return 400 `# this line    self.send_error(400, "Bad request syntax (%r)" % requestline)
`, werkzeug try log the error but request environ is not init.

Are you sure change the https scheme to http, and see this error again?

**Comment by allexeye** [comment]
Sorry, I missed this part, you are right it happens only for https
